# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='postman',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='quoted_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='title',
        ),
        migrations.AddField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='likes_user',
            field=models.ManyToManyField(related_name='liked_quotes', to='quotes.User'),
        ),
        migrations.AddField(
            model_name='quote',
            name='massage',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_posted', to='quotes.User'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
    ]
