# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20171007_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='massage',
            new_name='quote_text',
        ),
    ]
